# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fannypack
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  An open source HTML and CSS toolkit with prebuilt modules and a responsive design. Build the most awesome sites and applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://fannypack.persgroep.net # the base hostname & protocol for your site, e.g. http://example.com
github: https://github.com/depersgroep/fannypack

defaults:
  -
    scope:
      path: ""
      type: "docs" # collection in _docs folder
    values:
      layout: "default"
      modifier: "layout--fixed-header layout--sidebar theme--fp"
  -
    scope:
      path: "templates"
      type: "docs"
    values:
      layout: "templates"

collections:
  header:
    -
      page: "Documentation"
      url: "/layout/grid"
    -
      page: "Github"
      url: "https://github.com/depersgroep/fannypack"
  docs:
    output: true
    name: /:title
    category: /:path
    permalink: /:collection/:name

# Build settings
source: ./jekyll
destination: ./docs
markdown: kramdown
highlighter: rouge
permalink: pretty
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
