baseURL= "https://joggink.com/fannypack"
archetypeDir = "hugo/archetypes"
contentDir = "hugo/content"
themesDir = "hugo/themes"
staticDir = "./dist"
publishDir = "./docs"
languageCode = "en-us"
canonifyURLs = true
title = "Fannypack"
theme = "fannypack"
metadataformat = "toml"

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

# disableLiveReload = true

pygmentsUseClasses=true
pygmentsCodeFences = true

[blackfriday]
	smartDashes = false
	latexDashes = false
	extensions = ["noIntraEmphasis"]

[[menu.main]]
	name = "Documentation"
	url = "/layout/grid"
