baseURL= "https://fannypack.persgroep.be"
archetypeDir = "hugo/archetypes"
contentDir = "hugo/content"
themesDir = "hugo/themes"
staticDir = "./dist"
publishDir = "./docs"
languageCode = "en-us"
title = "Fannypack"
theme = "fannypack"
metadataformat = "toml"

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

# disableLiveReload = true

pygmentsUseClasses=true
pygmentsCodeFences = true

[blackfriday]
	smartDashes = false
	latexDashes = false
	extensions = ["noIntraEmphasis"]
