baseURL= "https://fannypack.persgroep.net/"
archetypeDir = "hugo/archetypes"
contentDir = "hugo/content"
themesDir = "hugo/themes"
staticDir = "./dist"
publishDir = "./docs"
languageCode = "en-us"
relativeURLs = true
canonifyURLs = true
title = "Fannypack"
theme = "fannypack"
metaDataFormat = "toml"
DefaultContentLanguage = "en"
enableRobotsTXT = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

# disableLiveReload = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
#pygmentsOptions = "linenos=table"

[params]
	favicon = ""
	description = "An open source HTML and CSS toolkit. With prebuilt modules and a responsive design you can build the most awesome sites and applications."
	facebook = ""
	twitter = "https://twitter.com/Fannypack"
	github = "https://github.com/depersgroep/fannypack"
	images = [""]

[blackfriday]
	smartDashes = false
	latexDashes = false
	extensions = ["noIntraEmphasis"]

[[menu.main]]
	name = "Documentation"
	url = "/layout/grid"
